# Generated by Django 3.2.5 on 2023-09-30 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('remark', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('firstname', models.TextField()),
                ('middlename', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField()),
                ('gender', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('date_hired', models.DateField()),
                ('salary', models.FloatField(default=0)),
                ('remark', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.department')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('remark', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sequence', models.TextField()),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('rank', models.TextField()),
                ('date_of_commence', models.DateTimeField(default=django.utils.timezone.now)),
                ('basic_salary', models.FloatField(default=0)),
                ('meal_allowance', models.TextField()),
                ('living_cost_allowance', models.TextField()),
                ('traveling_allowance', models.TextField()),
                ('special_allowance', models.TextField()),
                ('overtime', models.TextField()),
                ('ssb_deduction', models.TextField()),
                ('emergency_loan', models.TextField()),
                ('income_tax', models.TextField()),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('attachment', models.ImageField(default=None, upload_to='')),
                ('recruitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.recruitment')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sequence', models.TextField()),
                ('open_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_salary', models.TextField()),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.department')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('payment_type', models.TextField()),
                ('quantity', models.TextField()),
                ('amount', models.TextField()),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ImageField(default=None, upload_to='')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.department')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.position'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rank', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('remark', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', models.TextField()),
                ('working_day', models.TextField()),
                ('day_off', models.TextField()),
                ('check_in', models.DateField(default=django.utils.timezone.now)),
                ('check_out', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField()),
                ('status', models.IntegerField()),
                ('attachment', models.ImageField(default=None, upload_to='')),
                ('payroll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.payroll')),
            ],
        ),
    ]
